import { IRestaurantsList } from "../../interfaces/restaurants";

export const restaurants: IRestaurantsList = {
  total: 24,
  businesses: [
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg5",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg6",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg7",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg8",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg10",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg11",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg12",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg13",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg14",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg15",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg16",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg17",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg18",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg19",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "10E8RJkjfdcwgtyoPMjQ_Olg",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "1E8RJkjfdcwgtyoPMjQ_Olg",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg2",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg3",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg4",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
    {
      rating: 4,
      price: "$",
      phone: "+14152520800",
      id: "E8RJkjfdcwgtyoPMjQ_Olg20",
      alias: "four-barrel-coffee-san-francisco",
      is_closed: false,
      categories: [
        {
          alias: "coffee",
          title: "Coffee & Tea",
        },
      ],
      review_count: 1738,
      name: "Four Barrel Coffee",
      url: "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      coordinates: {
        latitude: 37.7670169511878,
        longitude: -122.42184275,
      },
      image_url:
        "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      location: {
        city: "San Francisco",
        country: "US",
        address2: "",
        address3: "",
        state: "CA",
        address1: "375 Valencia St",
        zip_code: "94103",
      },
      distance: 1604.23,
      transactions: ["pickup", "delivery"],
    },
  ],
  region: {
    center: {
      latitude: 37.767413217936834,
      longitude: -122.42820739746094,
    },
  },
};
